# Generated by Django 3.2 on 2022-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_userprofile_default_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_postcode',
            field=models.CharField(choices=[('Dublin 1', 'Dublin 1'), ('Dublin 2', 'Dublin 2'), ('Dublin 4', 'Dublin 4'), ('Dublin 6', 'Dublin 6'), ('Dublin 7', 'Dublin 7'), ('Dublin 8', 'Dublin 8'), ('Dublin 12', 'Dublin 12')], default='', max_length=10),
        ),
    ]
