# Generated by Django 3.2 on 2022-06-29 17:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20220629_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_slot',
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(default=datetime.date.today, help_text='DD-MM-YYYY'),
        ),
        migrations.AddField(
            model_name='order',
            name='timeslot',
            field=models.IntegerField(choices=[(0, '10:00 - 11:00'), (1, '11:00 - 12:00'), (2, '12:00 - 13:00'), (3, '13:00 - 14:00'), (4, '14:00 - 15:00'), (5, '15:00 - 16:00'), (6, '16:00 - 17:00'), (7, '17:00 - 18:00'), (8, '18:00 - 19:00'), (9, '19:00 - 20:00'), (10, '20:00 - 21:00')], default=8),
        ),
    ]
