# Generated by Django 3.2 on 2022-07-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_alter_order_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default='Dublin', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Ireland', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default='Dublin', max_length=10),
        ),
    ]
