# Generated by Django 3.2 on 2022-07-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20220701_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[(1, 'Dublin')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(choices=[(1, 'Ireland')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(choices=[(1, 'Dublin')], default=1, max_length=10),
        ),
    ]
