# Generated by Django 3.2 on 2022-07-03 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_delivery_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.AddField(
            model_name='order',
            name='eircode',
            field=models.CharField(default='EIRCODE', max_length=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='Ireland', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(default='Co. Dublin', max_length=10),
        ),
    ]
