# Generated by Django 3.2 on 2022-07-03 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_auto_20220703_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(default='IE', max_length=10),
        ),
    ]
