# Generated by Django 3.2 on 2022-07-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0011_auto_20220703_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='eircode',
            field=models.CharField(default='', max_length=7),
        ),
    ]
