# Generated by Django 3.2 on 2022-07-04 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_order_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postcode',
            field=models.CharField(choices=[('Dublin 1', 'Dublin 1'), ('Dublin 2', 'Dublin 2'), ('Dublin 4', 'Dublin 4'), ('Dublin 6', 'Dublin 6'), ('Dublin 7', 'Dublin 7'), ('Dublin 8', 'Dublin 8'), ('Dublin 12', 'Dublin 12')], default='', max_length=10),
        ),
    ]
