# Generated by Django 3.2 on 2022-07-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='product',
        ),
        migrations.AddField(
            model_name='rating',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
