# Generated by Django 3.2 on 2022-07-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20220707_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ManyToManyField(to='products.Product'),
        ),
    ]
