# Generated by Django 3.2 on 2022-07-10 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_rating_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='review',
            name='heading',
            field=models.CharField(default='', max_length=100),
        ),
    ]
